id = "rose-wine"
name = "Storm Rose Wine"
description = "A fork of Rose Pine."
version = "0.0.1"
schema_version = 1
authors = ["Michael Angerman <1809991+stormasm@users.noreply.github.com>"]
repository = "https://github.com/stormasm/rosewine"
